### ISSUE TITLE
Translate Text for Presskit

### ISSUE THREAD

**Issue by janwirwahn** [sensebox/sensebox.github.io#112]
This text should be integrated into the press kit and translated into English:

> **senseBox und openSenseMap**
> 
> Die senseBox ist ein Citizen Science Projekt, welches im Schüler- und Forschungslabor
> GI@School am Institut für Geoinformatik der Universität Münster entwickelt wurde. Bei
> diesem Projekt werden Do-It-Yourself Bausätze für Sensorstationen zusammen mit
> detaillierten Anleitungen interessierten Bürgerinnen und Bürgern bereitgestellt, um ihnen
> die Möglichkeit zu geben, sich an einer wissenschaftlichen Messkampagne für
> Umweltdaten mit Hilfe von Photonik-Technologien zu beteiligen.
> Hierfür wurde in dem Projekt die **senseBox:home** entwickelt: eine low-cost Wetterstation
> mit optischen Sensoren zur Messung von Helligkeit und UV-Licht, sowie Sensoren für
> Temperatur, Luftfeuchtigkeit und Luftdruck. Aktuell wird an mehreren Sensorerweiterungen
> gearbeitet, bei denen z.B. durch einen photonischen Feinstaubsensor
> Luftqualitätsmessungen möglich sind, oder mit einer Kamera der Wolkendeckungsgrad am
> Himmel bestimmt werden kann.
> Des Weiteren kommt die **senseBox:edu** in Schulen zum Einsatz, um Schülerinnen und
> Schülern ab der 7. Klassen die Grundlagen des Programmierens anhand von
> Microkontrollern und Umweltsensorik praktisch beizubringen.
> Um Schulen die Möglichkeit zu kooperativen Projekten zu geben und die Messungen mit
> der Öffentlichkeit zu teilen, wurde die **openSenseMap** entwickelt. Auf dieser webbasierten
> Plattform werden alle Messungen als Download oder Schnittstelle für
> Softwareanwendungen im Internet bereitgestellt.
> Die Forscher am Institut für Geoinformatik erhoffen sich durch die Kampagne großflächige
> und hochaufgelöste Messungen zu erhalten, mit denen in Zukunft gesellschaftlich
> relevante Fragestellungen zu lokalen Wetterphänomenen, Luft- und Gewässerqualität
> oder Verkehrsaufkommen beantwortet werden können.
> 
> [www.sensebox.de](https://www.sensebox.de)
> [www.opensensemap.org](https://www.opensensemap.org)

**Comment by benzmanu** [comment]
Wo soll das im Pressekit hin bzw wie?

**Comment by benzmanu** [comment]
senseBox and openSenseMap

The senseBox is a citizen science project, which was developed in the student lab and research laboratory GI@School at the Institute for Geoinformatics at the University of Münster. This project provides do-it-yourself construction kits for sensor stations with detailed instructions for interested citizens. This enables them to take part in a scientific measuring campaign on environmental data with the help of photonic technology.

This is why we developed senseBox:home: it is a low-cost weather station with optical sensors to measure not only the light intensity and ultraviolet light, but also the temperature, air moisture, and air-pressure. Currently we are working on several sensor extensions. Through their help it will be possible to measure the air quality with a photonic fine dust sensor or the degree of the cloud cover at the sky can be gauged by a camera.

Moreover, the senseBox:edu is used at schools to teach students grade seven and older the basics coding through mirco controllers and environmental sensor technology. 

In order to give schools the possibility for cooperating projects and to share their measurements with the public, we created the openSenseMap. On this web-based platform all measurements are available to download or offered on an interface for software applications online.

With this campaign, the researchers at the Institute for Geoinformatics expect to get large-scale and high-resolution measurements, with whom socially relevant questions about local weather phenomena, air quality, water quality or traffic volume can be answered in the future.

www.sensebox.de
www.opensensemap.org

**Comment by ubergesundheit** [comment]
Thanks @benzmanu Please close issues if everything in the issue is done.
